config/routes.rb
Rails.application.routes.draw do

  root 'homes#home'

  #Room
  resources :rooms, except: [:edit, :show]
  get "booking/:id", to: "rooms#booking", as: "booking"
  get "rooms/posts", to: "rooms#posts"
  get "rooms/search", to: "rooms#search"

  #Reservation
  resources :reservations, only: [:index, :show]
  post  "reservation/confirm", to: "reservations#confirm", as: "confirm"
  #get "reservation/confirm", to: "homes#index"
  post "reserve", to: "reservations#create"

  #get "reservations/new", to: "reservations#new"
  
  #User
  get 'users/show'
  #get 'users/edit', to: "users/passwords#edit"

  #User(device)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }



  devise_scope :user do
    get 'users/account' => 'users/registrations#account'
    patch 'users'    => 'users/registrations#update'
    get 'users/profile' => 'users/registrations#profile'    
  end
  patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'

  #resources :users, only: [:show, :edit]


end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :reserving_user, class_name: "User"
  belongs_to :reserved_room, class_name: "Room"
  validates :reserving_user_id, presence: true
  validates :reserved_room_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number_of_people, presence: true
  validates :amount, presence: true
  validates :reserving_user_id, uniqueness: { scope: :reserved_room_id } #一人のユーザは1つの部屋の重複予約はできない。

  #予約の日数、人数から合計金額を計算し、結果を返す(そしてコントローラで変数に格納) そして、終了日より開始日が後になっていたらfalseを返す。
  def calculate_amount
    days = self.calculate_number_of_date
    #合計金額=1日あたりの金額*人数*日数
    return false if ( days == false )
    amount = Room.find(self.reserved_room_id).price_per_person_per_night * number_of_people * days 
    return amount 
  end

  #予約日数を返す
  def calculate_number_of_date
    return false unless self.start_date || self.end_date
    start_date = self.start_date 
    end_date = self.end_date
    start_day = start_date.day                #開始日
    end_day = end_date.day                    #終了日
    start_month = start_date.month            #開始月
    end_month = end_date.month                #終了月
    start_year = start_date.year              #開始年
    end_year = end_date.year                  #終了年
    number_of_people = self.number_of_people  #人数
    last_day = Date.new( start_year, start_month, -1).day  #開始日の末日(28日or29日or30日or31日)を取得.(計算用)

    return false if date_is_invalid?(start_day, end_day)  #入力した日付が前後していればエラーメッセージを追加し、falseを返す
    
    if ( start_month == end_month )                # if 開始日と終了日が同じ月であるなら。
      days = end_day - start_day                   #日数を計算
    elsif ( start_month != end_month )             # eslif 開始日と終了日が異なる月であるなら。
      days = ( last_day - start_day) + end_day     #日数を計算
    end
    days
  end

  #入力した日付が前後していればエラーメッセージを追加し、falseを返すメソッド
  def date_is_invalid?(start_date, end_date)
    if self.start_date.past?
      errors.add(:start_date, "開始日には今日以降の日付を選択してください")
    elsif start_date == end_date
      errors.add(:start_date, "開始日と終了日に同じ日付を選択しています")
    elsif start_date > end_date
      errors.add(:start_date, "開始日が終了日より後の日付になっています")
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  #予約済みルーム一覧
  #reservations GET    /reservation      #reservations GET    /reservations(.:format)   reservations#index
  def index
    @reservations = Reservation.order(created_at: :asc)
    @rooms = Room.all
    @users = User.all
  end


  #confirm   POST   "/reservations/confirm"
  def confirm

    @reservation = Reservation.new(reservation_confirm_params)
    @user = current_user
    @room = Room.find(@reservation.reserved_room_id)
    if @reservation && @amount = @reservation.calculate_amount
      #@amountに合計金額をいれた結果、値が入っているなら。
      return
    elsif @reservation.invalid?
      flash[:danger] = t('.the_reservation_was_not_created_successfully')
      redirect_to booking_url(@room)
    end
  end

  #reserve POST   /reserve
  def create
    @reservation = Reservation.create(reservation_params)
    @room = Room.find(@reservation.reserved_room_id)
    if params[:back]
      render "rooms/booking"

    elsif @reservation.valid?

      flash[:success] = "予約を確定しました"
      redirect_to reservation_url(@reservation)
    else

      render "rooms/booking"
    end
  end

  #reservation   get   /reservation/:id
  def show
    
    @reservation = Reservation.find(params[:id])
  end

  private

  def reservation_confirm_params
    params.permit(:start_date, :end_date,
                  :number_of_people, :reserving_user_id,
                  :reserved_room_id)
  end
  def reservation_params
    params.require(:reservation).permit(:reserving_user_id, :reserved_room_id,:start_date, 
                  :end_date, :number_of_people,:amount)
  end


end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.erb
<div class="confirm-wrap">
  <div class="confirm-content">
    <h4><%= t('.confirmation_of_reservation_details') %></h4>
    <h5>¥ <%= @amount %> / <%= t('.day') %></h5>
    <div class="confirm-details">
      <%= form_with model: @reservation, url: reserve_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :reserving_user_id, :value => current_user.id %>
        <%= f.hidden_field :reserved_room_id, :value => @room.id %>
        <%= f.hidden_field :number_of_people, :value => @reservation.number_of_people %>

        <p><%= t('.start_date') %></p>
        <%= f.text_field :start_date, :value => @reservation.start_date, readonly: true %>
        <p><%= t('.end_date') %></p>
        <%= f.text_field :end_date, :value => @reservation.end_date, readonly: true %>
        <p class="border-bottom-gray"><%= t('.days_of_use') %> : <%= @reservation.calculate_number_of_date %><%= t('.day')%></p>
        <p class="border-bottom-gray"><%= t('.number_of_people') %> : <%= @reservation.number_of_people %><%= t('.person') %></p>
        <p><%= t('.amount') %></p>
        <%= f.text_field :amount, :value => @amount, readonly: true %>
        <p class="border-bottom-gray"><%= t('.if_you_are_satisfied_with_the_above_contents_please_press_confirm_reservation') %></p>

        <%= f.submit t('.confirm_reservation'), class:"confirm-btn confirm-submit-btn" %>
        <%= f.submit t('.back'), name: 'back', class:"confirm-btn confirm-back-btn" %>

      <% end %>

    </div>

app/views/reservations/confirmation.html.erb
<div class="confirm-wrap">
  <div class="confirm-content">
    <h4><%= t('.confirmation_of_reservation_details') %></h4>
    <h5>¥ <%= @reservation.amount %> / <%= t('.day') %></h5>
    <div class="confirm-details">
      <%= form_with model: @reservation, url: reserve_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :reserving_user_id, :value => @user.id %>
        <%= f.hidden_field :reserved_room_id, :value => @room.id %>

        <p><%= t('.start_date') %></p>
        <%= f.text_field :start_date, :value => @reservation.start_date, readonly: true %>
        <p><%= t('.end_date') %></p>
        <%= f.text_field :end_date, :value => @reservation.end_date, readonly: true %>
        <p class="border-bottom-gray"><%= t('.days_of_use') %> : <%= @reservation.calculate_number_of_date %><%= t('.day')%></p>
        <p class="border-bottom-gray"><%= t('.number_of_people') %> : <%= @reservation.number_of_people %><%= t('.person') %></p>
        <p><%= t('.amount') %>
        <%= f.text_field :amount, :value => @reservation.amount, readonly: true %>
        <p class="border-bottom-gray"><%= t('.if_you_are_satisfied_with_the_above_contents_please_press_confirm_reservation') %></p>
        <%= f.submit t('.confirm_reservation'), class:"confirm-btn confirm-submit-btn" %>
        <%= f.submit t('.back'), name: 'back', class:"confirm-btn confirm-back-btn" %>

      <% end %>

    </div>

app/views/reservations/index.html.erb
<div class="res-wrap">
  <div class="res-room-wrap">
  <h4><%= t('.list_of_reserved_rooms') %></h4>
    <div class="res-content">
      <table>
        <tr class="res-th">
          <th class="res-room-image"><%= t('.room_image') %></th>
          <th class="res-room-name"><%= t('.room_name') %></th>
          <th class="res-room-introduction"><%= t('.room_introduction') %></th>
          <th class="res-amount"><%= t('.amount') %></th>
          <th class="res-start"><%= t('.start_date') %></th>
          <th class="res-end"><%= t('.end_date') %></th>
          <th class="res-create-date"><%= t('.reservation_time') %></th>
        </tr>
      </table>

      <table>
        <% @reservations.each do |reservation| %>
          <% room = @rooms.find(reservation.reserved_room_id) %>
          <tr class="res-td">
            <td class="res-room-image"><%= image_tag room.display_image(100, 80) %></td>
            <td class="res-room-name"><%= link_to room.room_name, booking_path(room),class:"col-blue" %></td>
            <td class="res-room-introduction"><%= room.room_introduction %></td>
            <td class="res-amount"><%= reservation.amount %></td>
            <td class="res-start"><%= reservation.start_date %></td>
            <td class="res-end"><%= reservation.end_date %></td>
            <% time = reservation.created_at %>
            <td class="res-create-date"><%= time.strftime("%Y/%m/%d") %><p><%= time.strftime("%H:%M") %></p></td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="show-wrap">
  <div class="show-content">
    <div class="show-row">
      <ul class="show-ul border-bottom-gray">
        <li><%= t('.reserved_room') %></li>
        <li><%= @reservation.reserved_room.room_name %></li>
      </ul>
    </div>

    <div class="show-row">
      <ul class="show-ul border-bottom-gray">
        <li><%= t('.start_date') %></li>
        <li><%= @reservation.start_date %></li>
      </ul>
    </div>


    <div class="show-row">
      <ul class="show-ul border-bottom-gray">
        <li><%= t('.end_date') %></li>
        <li><%= @reservation.end_date %></li>
      </ul>
    </div>


    <div class="show-row">
      <ul class="show-ul">
        <li><%= t('.amount') %></li>
        <li><%= "#{@reservation.amount}#{t('.unit')}" %></li>
      </ul>
    </div>

  </div>
</div>