config/routes.rb
Rails.application.routes.draw do

  root 'homes#home'

  #Room
  resources :rooms, except: [:edit, :show]
  get "booking/:id", to: "rooms#booking", as: "booking"
  get "rooms/posts", to: "rooms#posts"
  get "rooms/search", to: "rooms#search"

  #Reservation
  resources :reservations, only: [:index, :show]
  post  "reservation/confirm", to: "reservations#confirm", as: "confirm"
  #get "reservation/confirm", to: "homes#index"
  post "reserve", to: "reservations#create"

  #get "reservations/new", to: "reservations#new"
  
  #User
  get 'users/show'
  #get 'users/edit', to: "users/passwords#edit"

  #User(device)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }



  devise_scope :user do
    get 'users/account' => 'users/registrations#account'
    patch 'users'    => 'users/registrations#update'
    get 'users/profile' => 'users/registrations#profile'    
  end
  patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'

  #resources :users, only: [:show, :edit]


end

app/models/room.rb
class Room < ApplicationRecord
  # 外部キーをデフォルトのuser_idをowner_idに変更する
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  before_save   :set_room_introduction
  default_scope -> { order(created_at: :desc) }
  has_one_attached :image
  validates :room_name, presence: true, uniqueness: { scope: :owner_id }
  validates :room_introduction, presence: true, length: { maximum: 50 }
  validates :address, presence: true, uniqueness: true
  validates :price_per_person_per_night, presence: true
  validates :owner_id, presence: true

  validates :image, presence: true,
                    content_type: { in: %w[image/jpeg image/gif image/png],
                      message: "有効な画像形式である必要があります" },
                      size:         { less_than: 5.megabytes,
                      message: "5MB未満である必要があります" }
                      
  # 表示用のリサイズ済み画像を返す
  def display_image(width, height)
    image.variant(resize_to_limit: [width, height])
  end

  #検索フォームに入力がある場合、addressカラムに「入力された文字列」が含まれるルームを返す
  def self.search_area(search)
    return Room.all unless search
    Room.where(['address LIKE ?', "%#{search}%"])
  end
  #検索フォームに入力がある場合、room_nameカラムまたはroom_introductionカラムに「入力された文字列」が含まれるルームを返す
  def self.search_keyword(search)
    return Room.all unless search
    Room.where(['room_name LIKE ? OR room_introduction LIKE ?', "%#{search}%", "%#{search}%"])
  end


  private
    #ルームの紹介文がnilなら空文字列を代入する(before_save)
    def set_room_introduction
      self.room_introduction = "" if ( self.room_introduction == nil )
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:posts, :new, :create, :reserve]

  #rooms  GET    /rooms
  def posts
    @rooms = current_user.rooms
  end

  #new_room GET    /rooms/new ルーム登録画面
  def new
    @user = current_user
    @room = Room.new
  end

  #rooms  POST   /rooms
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = t('.room_was_successfully_created')
      redirect_to booking_url(@room)
    else
      flash[:danger] = t('.room_save_failed')
      render :new
    end
  end

  #room  GET    /rooms/:id
  def booking
    @room = Room.find(params[:id])
    @user = User.find(@room.owner_id)
  end

  #rooms_search GET /rooms/search
  def search
    if params[:search][:address].present?
      @rooms = Room.search_area(params[:search][:address])
      @searching_address = params[:search][:address]
    else
      @rooms = Room.search_keyword(params[:search][:keyword])
      @searching_keywords = params[:search][:keyword]
    end
  end


  private
    def room_params
      params.require(:room).permit(:room_name, :price_per_person_per_night,
                                  :owner_id, :address, :image,
                                  :room_introduction)
    end


    def room_search_params
      params.fetch(:search, {}).permit(:room_name, :address)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/booking.html.erb
<div class="booking-wrap">

  <div class="booking-content">


    <div class="booking-left">
      <div class="booking-image"> <!-- BookingPageの画像 -->
        <%= image_tag @room.display_image(500, 410) %>
      </div>

      <div class="booking-details"><!-- BookingPageのタイトル、住所など -->

        <div class="details-icon border-bottom-gray">
            <% if @user.image.attached? %>
              <%= image_tag @room.owner.display_image(50, 50) %>
            <% else %>
              <i class="setting-user-icon fas fa-user-circle"></i>
            <% end %>
        </div>

        <div class="details-name">
            <p id="details-room-name"><%= @room.room_name %></p>
        </div>

        <div class="details-address border-bottom-gray">
          <p id="details-address"><%= @room.address %></p>
        </div>

        <div class="details-introduction border-bottom-gray">
          <p><%= @room.room_introduction %></p> 
        </div>

      </div>  


    </div>
  

    <div class="booking-right">
        <div class="setting-right-content" id="booking-form">
          <%= form_with model: @reservation, url: confirm_path, method: :post, local: true do |f| %>

            <ul>
              <% if user_signed_in? %>
                <%= f.hidden_field :reserving_user_id, value: current_user.id %> 
                <%= f.hidden_field :reserved_room_id, value: @room.id %>
              <% end %>
              <li>
                <span>¥ <%= @room.price_per_person_per_night %> / <%= t('.day') %></span>
              </li>

              <li>
                <span><%= t('.start_date') %></span>
                <span><%= f.date_field :start_date %></span>
              </li>

              <li>
                <span><%= t('.end_date') %></span>
                <span><%= f.date_field :end_date %></span>
              </li>

              <li>
                <span><%= t('.number_of_people') %></span>
                <span><%= f.number_field :number_of_people %></span>
              </li>
              <% if user_signed_in? %>
                <li>
                  <%= f.submit t('.reserve'), class:"submit-btn-profile" %>
                </li>
              <% else %>
                <li>
                  <%= link_to t(".signin"), new_user_session_path, class:"booking-signin-btn" %>
                </li>
              <% end  %>
            </ul>
          <% end %>
        </div>

      </div>  

  </div>



</div>

app/views/rooms/index.html.erb
<h1>予約済みルーム一覧</h1>

<% @rooms.each do |room| %>
  <p><%= link_to room.room_name, booking_path(room) %></p>
<% end %>

app/views/rooms/new.html.erb
<div class="setting-wrap">
  <div class="setting-left">
    <div class="setting-left-content">
      <ul>
        <li><%= link_to t('.information'), users_account_path, id:"setting-toggle" %></li>
      </ul>
    </div>
  </div>

  <div class="setting-right">
    <div class="setting-right-new">
      <%= form_with model: @room, url: rooms_path, local: true do |f| %>
          
        <ul class="room-new-ul">
          <li class="border-bottom-gray" id="setting-title">
            <span><%= t('.registration_room') %></span>
            <span></span>
          </li>

          <%= render "devise/shared/error_messages", resource: @room %>

          <li class="border-bottom-gray font-bold">
            <span><%= t('.room_name') %> <div class="required-new">必須</div></span>
            <span><%= f.text_field :room_name, placeholder:"ルーム名を入力" %></span>
          </li>

          <li class="border-bottom-gray font-bold">
            <span><%= t('.room_introduction') %> <div class="required-new">必須</div></span>
            <span><%= f.text_area :room_introduction,  placeholder:"ルーム説明を入力" %></span>
          </li>

          <li class="border-bottom-gray font-bold">
            <span><%= t('.price') %> <div class="required-new">必須</div></span>
            <span><%= f.text_field :price_per_person_per_night, class:"#", id:"aaa" , placeholder:"1日あたりの料金を入力" %></span>
          </li>

          <li class="border-bottom-gray font-bold">
            <span><%= t('.address') %> <div class="required-new">必須</div></span>
            <span><%= f.text_field :address, class:"#", id:"aaa" , placeholder:"住所を入力" %></span>
          </li>

          <li class="border-bottom-gray font-bold">
            <span><%= t('.room_image') %> <div class="required-new">必須</div></span>
            <span><%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %></span>
          </li>

          <li id="setting-submit-btn">
            <span><%= f.submit t('.registration'), class:"submit-btn-profile room_registration" %></span>
            <span></span>
          </li>
        </ul>

      <% end %>

    </div>  
  </div>

app/views/rooms/posts.html.erb
<div class="reg-wrap">
  <div class="reg-room-wrap">
  <h4><%= t('.list_of_registrated_rooms') %></h4>
    <div class="reg-content">
      <table>
        <tr class="reg-th">
          <th class="reg-room-image"><%= t('.room_image') %></th>
          <th class="reg-room-name"><%= t('.room_name') %></th>
          <th class="reg-room-introduction"><%= t('.room_introduction') %></th>
          <th class="reg-price"><%= t('.price') %></th>
          <th class="reg-create-date"><%= t('.created_at') %></th>
        </tr>
      </table>

      <table>
        <% @rooms.each do |room| %>
          <tr class="reg-td">
            <td class="reg-room-image"><%= image_tag room.display_image(100, 80) %></td>
            <td class="reg-room-name"><%= link_to room.room_name, booking_path(room), class:"col-blue" %></td>
            <td class="reg-room-introduction"><%= room.room_introduction %></td>
            <td class="reg-price"><%= room.price_per_person_per_night %></td>
            <% time = room.created_at %>
            <td class="res-create-date"><%= time.strftime("%Y/%m/%d") %><p><%= time.strftime("%H:%M") %></p></td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="search-wrap">
  <div class="search-content">
    <h4><%= "#{t('.search_result')} : #{@rooms.count}#{t('.case')}" %></h4>
    <% if @searching_address&.present? %>
      <h4 class="searching-words"><%= "#{t('.searching_address')} :「 #{@searching_address} 」" %></h4>
    <% end %>
    <% if @searching_keywords&.present?  %>
      <h4 class="searching-words"><%= "#{t('.searching_keywords')} :「 #{@searching_keywords} 」" %></h4>
    <% end %>

    <% @rooms.each do |room| %>
        <%= link_to booking_path(room) do %>
          <div class="search-item">
            <div class="search-inner">
                <div class="search-image">
                  <%= image_tag room.display_image(220,200) %>
                </div>
                <div class="search-item-detail">
                  <h5><%= room.room_name %></h5>
                  <p class="search-address"><%= room.address %></p>
                  <p class="search-price">¥ <%= room.price_per_person_per_night %></p>
                </div>
            </div>
          </div>
        <% end %>
    <% end %>
  </div>
</div>