config/routes.rb
Rails.application.routes.draw do

  root 'homes#home'

  #Room
  resources :rooms, except: [:edit, :show]
  get "booking/:id", to: "rooms#booking", as: "booking"
  get "rooms/posts", to: "rooms#posts"
  get "rooms/search", to: "rooms#search"

  #Reservation
  resources :reservations, only: [:index, :show]
  post  "reservation/confirm", to: "reservations#confirm", as: "confirm"
  #get "reservation/confirm", to: "homes#index"
  post "reserve", to: "reservations#create"

  #get "reservations/new", to: "reservations#new"
  
  #User
  get 'users/show'
  #get 'users/edit', to: "users/passwords#edit"

  #User(device)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }



  devise_scope :user do
    get 'users/account' => 'users/registrations#account'
    patch 'users'    => 'users/registrations#update'
    get 'users/profile' => 'users/registrations#profile'    
  end
  patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'

  #resources :users, only: [:show, :edit]


end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-wrap">
    <p>© 2021 POTEPAN.INC.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header-left">
    <div class="header-logo">
      <%= link_to image_tag("pote_share_logo.png", class:"header-logo" ), root_path %>  
    </div>
    
    <%= form_with(scope: :search, url: rooms_search_path, method: :get, local: true, class:"header-form") do |f| %>

      <div class="header-search-area">
        <i class="fas fa-map-marker-alt"></i>
        <%= f.text_field :address, class:"search-form", placeholder:"エリア" %>
      </div>
      <div class="header-search-keyword">
        <i class="fas fa-search"></i>
        <%= f.text_field :keyword, class:"search-form", placeholder:"キーワード" %>
      </div>
      
      <%= f.submit class:"hidden_submit"%>
    <% end %>
  
  </div>

  <div class="header-right">

    <% if user_signed_in? %>
      <li class="login-user-name"><%= current_user.name %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <% if current_user.image.attached? %>
              <%= image_tag current_user.display_image(50, 50), class:"user-icon header-round-image" %>
            <% else %>
              <i class="user-icon fas fa-user-circle"></i>
            <% end %>
        </a>
        <ul class="dropdown-menu dropdown-menu-right">
          <li><%= link_to "ルーム登録", new_room_path %></li>
          <li><%= link_to "予約済みルーム一覧", reservations_path %></li>
          <li><%= link_to "登録済みルーム一覧", rooms_posts_path %></li>
          <li><%= link_to "設定", users_account_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

    <% else %>
      <li><%= link_to "ログイン", new_user_session_path, class:"link login-link"%></li>
      <li><%= link_to "登録", new_user_registration_path, class:"link registration-link" %></li>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoteShareAppNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- レスポンシブ対応 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes"> 
    <!-- Font awesome -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="wrap">

      <div class="notification">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>

      <%= yield %>
    
    </div>
    
    <%= render "layouts/footer" %>
  </body>
</html>